name: bus_attendance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  # Or latest version
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.13.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
